environment:
  myuser:
    secure: BNlXevLtF9e2aPA67RkRlg==
  mypass:
    secure: UVcVBPUuJmH6Dargd2JZHitYoqNavVuBWWeJ8fvarLfSahvVhAAlXsnO2roo/75L
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\devtools\\appveyor-ci\\run_with_env.cmd"
    PYTHONUNBUFFERED: 1

  matrix:
    - PYTHON: "C:\\Miniconda"
      CONDA_PY: "27"
      CONDA_NPY: "19"

    - PYTHON: "C:\\Miniconda-x64"
      CONDA_PY: "27"
      CONDA_NPY: "112"
      ARCH: "64"

    - PYTHON: "C:\\Miniconda3"
      CONDA_PY: "35"
      CONDA_NPY: "113"

    - PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "36"
      CONDA_NPY: "113"
      ARCH: "64"

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - conda config --add channels conda-forge
  - conda install -yq conda-build 

build: false

test_script:
  - "%CMD_IN_ENV% conda build --quiet devtools\\conda-recipe"

