package:
  name: bhmm-dev
  version: 0.0.0

source:
  path: ../..


build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - scipy
    - msmtools
    - six

  run:
    - python
    - cython
    - numpy
    - scipy
    - msmtools
    - six

test:
  requires:
    - pytest
  imports:
    - bhmm
  commands:
    - pytest --pyargs bhmm -s -v --doctest-modules

about:
  home: https://github.com/choderalab/bhmm
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  summary: Bayesian hidden Markov models for analysis of single-molecule trajectory data
